// Fuente única de verdad del sitio. Edita aquí y corre `node src/build.mjs`.
// Todo lo que está aquí sale de los proyectos reales (READMEs, propuestas y auditorías).

export const sitio = {
  nombre: 'Alan Méndez',
  nombreCompleto: 'Alan Daniel Méndez Jiménez',
  titulo: 'Software a medida para negocios locales',
  dominio: 'https://alanmendez.vercel.app', // cuando compres alanmendez.dev: vercel domains add alanmendez.dev y cambia esto
  telefonoE164: '524661603682',
  telefonoBonito: '+52 466 160 3682',
  email: 'alannicanor62@gmail.com',
  github: 'https://github.com/Alan20111',
  ciudad: 'Celaya',
  region: 'Guanajuato',
  mensajeWhatsApp: 'Hola Alan, vi tu sitio web y quiero agendar una demo para mi negocio',
  // Ficha de Google Business: pega aquí el enlace "Compartir perfil" cuando la tengas
  googleBusiness: '',
  // Analítica: Vercel Web Analytics se activa en el dashboard del proyecto (Analytics → Enable).
  // Si prefieres GA4, pon tu ID (G-XXXXXXX) y el sitio lo carga solo.
  ga4: '',
};

// Estados: produccion | entregado | propuesta | academico
export const casos = [
  {
    slug: 'evaluafacil',
    nombre: 'Evalúa Fácil',
    cliente: 'Docentes de bachillerato (DGETI / SEP)',
    sector: 'Educación',
    estado: 'produccion',
    estadoTexto: 'En producción · producto propio',
    fecha: '2026',
    resumen: 'Plataforma web + app Android para llevar calificaciones, asistencia y actas bajo la Nueva Escuela Mexicana, con IA para calificar y planear.',
    problema: [
      'Los docentes llevaban calificaciones, listas y actas en Excel y cuadernos; el sistema institucional es rígido y no ayuda en el día a día.',
      'Los alumnos de bachillerato muchas veces no tienen correo electrónico, así que las plataformas típicas no les sirven.',
      'Calificar entregables, redactar planeaciones y armar exámenes consume horas fuera del aula.',
    ],
    solucion: [
      'Plataforma web (React + Firebase) y app Android con la misma cuenta. Los alumnos entran sin correo: usuario generado, QR o código de 6 caracteres.',
      'Alta masiva desde Excel, asistencia desde el celular generada del horario, cuestionarios y exámenes con gráficas por reactivo, banco de reactivos y rúbricas.',
      'IA con créditos prepagados: califica entregables con rúbrica, genera reactivos, planeaciones didácticas y diagnósticos de grupo.',
      'Cierre de parcial en una acción (reversible), copia de asignatura para el siguiente ciclo y exportación a Excel y PDF listos para entregar.',
    ],
    resultado: [
      'En producción con dominio propio (evaluafacil.mx) y app Android (APK firmado, v1.0.11) con la misma cuenta.',
      'Seguridad probada: reglas de Firestore con pruebas automáticas, calificaciones y créditos solo escribibles desde el servidor.',
      'Cierre de parcial y acta en minutos en lugar de tardes completas.',
    ],
    stack: ['React 19', 'Vite', 'Tailwind', 'Firebase', 'Cloud Functions', 'Capacitor (Android)', 'Vercel', 'Claude API'],
    url: 'https://www.evaluafacil.mx',
    demo: {
      titulo: 'Evalúa Fácil',
      descripcion: 'Plataforma completa (docente y alumno). Requiere cuenta: pídeme una cuenta de prueba por WhatsApp y te la activo al momento.',
      url: 'https://www.evaluafacil.mx',
      tipo: 'Producto en producción',
      credenciales: null, // TODO: cuando exista la cuenta demo, poner { usuario: '...', clave: '...' }
      solicitar: true,
    },
  },
  {
    slug: 'bazargirl',
    nombre: 'The Bazar Girl',
    cliente: 'Bazar de maquillaje y accesorios (venta por WhatsApp)',
    sector: 'Comercio',
    estado: 'produccion',
    estadoTexto: 'En producción',
    fecha: 'Ago – Sep 2026',
    resumen: 'Catálogo web donde las clientas apartan y un panel desde el celular para pedidos, existencias, cierre del día y publicaciones para WhatsApp.',
    problema: [
      'Todo se vendía en un grupo de WhatsApp: fotos sueltas, apartados en notas y existencias en la cabeza.',
      'Productos "congelados" por clientas que apartaban y no respondían; sin forma de saber cuánto se vendió en el día.',
      'Publicar el catálogo cada semana era armar imágenes y mensajes a mano.',
    ],
    solucion: [
      'Catálogo web instalable (PWA) por categorías y tonos; la clienta aparta desde el celular y la dueña confirma por WhatsApp.',
      'Panel con pedidos en cuatro etapas (por confirmar → confirmados → listos → entregados), caducidad automática a las 48 h que regresa el stock, cierre del día y puntos de entrega con horarios.',
      'Pestaña "Publicar": arma la imagen y el mensaje listos para el grupo de WhatsApp.',
      'Base de datos Supabase con seguridad por filas en las 12 tablas: el costo de cada producto nunca sale al público.',
    ],
    resultado: [
      'En producción en bazargirl.pages.dev; el panel se usa desde el teléfono como app.',
      'Cero apartados eternos: el stock se libera solo si nadie confirma.',
      'Manual del panel entregado (botón por botón) y seguridad verificada contra el proyecto real el 14-sep-2026.',
    ],
    stack: ['React 19', 'Vite', 'Supabase (Postgres + RLS)', 'Leaflet', 'PWA', 'Cloudflare Pages'],
    url: 'https://bazargirl.pages.dev',
    demo: {
      titulo: 'Bazar Girl · catálogo',
      descripcion: 'Catálogo de muestra con fotos y tonos reales. El panel de la dueña es privado; te lo muestro en llamada.',
      url: 'https://bazargirl.pages.dev/demo/',
      tipo: 'Catálogo demo',
      credenciales: null,
    },
  },
  {
    slug: 'cafeluna',
    nombre: 'Café Luna',
    cliente: 'Demo propia · sistema para cafeterías',
    sector: 'Alimentos',
    estado: 'demo',
    estadoTexto: 'Demo en vivo',
    fecha: 'Sep 2026',
    resumen: 'Kiosko, app del cliente, pantalla de cocina y panel del dueño, los cuatro sincronizados en vivo: lo que pasa en uno aparece al instante en los demás.',
    problema: [
      'En una cafetería con fila, el cliente espera para ordenar y otra vez para pagar.',
      'Las comandas se gritan o se anotan en papel: se pierden, se repiten y nadie sabe cuál va primero.',
      'Al cierre del día se sabe cuánto se vendió, pero no cuánto quedó ni qué producto deja más.',
      'La lealtad se lleva en tarjetas de cartón que el cliente olvida o pierde.',
    ],
    solucion: [
      'Kiosko de autoservicio en el mostrador y pedido desde el teléfono del cliente por QR; el cobro se pide desde el teléfono y se aprueba en la terminal.',
      'Pantalla de cocina con cola por orden de llegada: los pagos con terminal entran solos y solo los de efectivo piden confirmación.',
      'Panel del dueño: ventas del mes, utilidad neta, margen, ticket promedio, a dónde va cada peso, qué producto deja más, inventario y reinversión sugerida.',
      'Estrellas de lealtad ligadas al teléfono del cliente, sin tarjetas ni app que instalar.',
      'Todo se sincroniza por WebSocket con un Durable Object de Cloudflare: un solo estado compartido para las cuatro pantallas.',
    ],
    resultado: [
      'Demo pública y funcional: abre kiosko, cocina y admin en dos ventanas y verás el pedido moverse entre ellas al instante.',
      'Sin instalar nada: corre en el navegador de cualquier tablet, teléfono o computadora del negocio.',
      'Los datos son ficticios y se reinician con un botón, así que cualquiera puede jugar con ella sin romper nada.',
    ],
    stack: ['HTML/CSS/JS', 'Cloudflare Pages', 'Workers + Durable Objects', 'WebSocket', 'PWA'],
    url: 'https://cafeluna.pages.dev',
    demo: {
      titulo: 'Café Luna · sistema completo',
      descripcion: 'Empieza por el panel de demo: desde ahí abres kiosko, cocina y admin. Para el mejor efecto, ábrelos en dos ventanas y haz un pedido.',
      url: 'https://cafeluna.pages.dev/hub',
      urlPanel: 'https://cafeluna.pages.dev/admin',
      tipo: 'Demo en vivo',
      credenciales: null,
    },
  },
  {
    slug: 'mediconsulta',
    nombre: 'MediConsulta',
    cliente: 'Consultorio médico privado',
    sector: 'Salud',
    estado: 'entregado',
    estadoTexto: 'Entregado · en uso',
    fecha: 'Jul – Ago 2026',
    resumen: 'Programa de escritorio para Windows: pacientes, consultas, recetas con membrete, agenda y respaldos automáticos. Sin internet, sin mensualidades.',
    problema: [
      'Más de 1,500 expedientes en un sistema anterior que ya no se podía mantener, con pacientes duplicados y recetas hechas a mano.',
      'El consultorio necesitaba algo que funcionara sin internet, sin depender de un proveedor y sin cuotas mensuales.',
      'Cambiar de computadora o respaldar la información era un riesgo.',
    ],
    solucion: [
      'Aplicación de escritorio (C# .NET 8, WPF) en un solo archivo .exe: pacientes, consultas, 10 diseños de receta con membrete y firma, agenda y catálogo de medicamentos.',
      'Toda la información vive en un archivo: cambiar de equipo es copiar y pegar. Respaldos automáticos (últimos 30) sin cerrar el programa.',
      'Migración del sistema anterior con deduplicación de expedientes y numeración consecutiva conservada.',
      'Licencia por computadora activable por WhatsApp (código de instalación → código de activación) y portal del proveedor para administrar clientes.',
    ],
    resultado: [
      'Entregado y en uso diario en el consultorio con su impresora de recetas.',
      '1,041 pruebas automáticas que codifican fallos reales encontrados en operación (expediente repetido, media hoja desperdiciada, etc.).',
      'Sincronización entre dos computadoras (v1.1) y versión Java en curso para macOS/Linux.',
    ],
    stack: ['C# 12', '.NET 8', 'WPF', 'SQLite', 'QuestPDF', 'Material Design', 'Java 21 (port)'],
    url: '',
    demo: {
      titulo: 'MediConsulta · recorrido de pantallas',
      descripcion: 'Maqueta de revisión con las pantallas reales del programa (activación, pacientes, consulta, receta). Datos de ejemplo.',
      url: 'demos/mediconsulta/',
      tipo: 'Recorrido interactivo',
      credenciales: null,
    },
  },
  {
    slug: 'aglaia',
    nombre: 'AGLAIA Nail Studio',
    cliente: 'Estudio de uñas · Celaya, Gto.',
    sector: 'Belleza',
    estado: 'propuesta',
    estadoTexto: 'Propuesta + maqueta navegable',
    fecha: 'Sep 2026',
    resumen: 'Sitio con agenda 24/7, anticipo en línea, cuenta de clienta con lealtad y referidas, y panel que responde "¿cuánto me quedó?".',
    problema: [
      'Cada cita eran de 6 a 12 mensajes por Instagram y WhatsApp; quien escribía a las 11 pm o en horario de clases muchas veces ya no volvía.',
      'Anticipos por comprobante en el chat: revisar la app del banco y citas "apartadas" que nunca pagaron.',
      'Tarjetas de lealtad de cartón que se pierden y referidas que no se pueden rastrear ni premiar.',
    ],
    solucion: [
      'Sitio público con servicios, precios y diseños; agenda que solo muestra horas realmente libres y anticipo de $100 con Mercado Pago (tarjeta, OXXO, SPEI).',
      'Confirmación y recordatorio automáticos por correo con folio y QR; si el anticipo no llega en 24 h, el hueco se libera solo.',
      'Cuenta de clienta con sellos de lealtad, historial, cupones y código de referida.',
      'Panel por preguntas: Hoy · Dinero · Ventas · Citas · Insumos · Clientas · Reportes. Escanea el QR, suma el sello y cobra en 10 segundos.',
    ],
    resultado: [
      'Maqueta navegable de sitio y panel, planes comparativos y propuesta de 12 páginas entregados a la clienta.',
      'Meta: agendar en 2 minutos sin intervención y −4 h de chat a la semana.',
      'El sistema se paga con +7 citas al mes (ticket promedio $258).',
    ],
    stack: ['HTML/CSS/JS', 'Chart.js', 'Mercado Pago', 'Cloudflare Pages + D1', 'Resend'],
    url: 'https://aglaianails.pages.dev',
    demo: {
      titulo: 'AGLAIA · sitio + panel',
      descripcion: 'Agenda una cita de prueba, paga el anticipo simulado y luego entra al panel de la dueña.',
      url: 'https://aglaianails.pages.dev',
      urlPanel: 'https://aglaianails.pages.dev/admin',
      tipo: 'Maqueta navegable',
      credenciales: { etiqueta: 'PIN del panel', usuario: null, clave: '1234', nota: 'Es vista previa: cualquier PIN entra.' },
    },
  },
  {
    slug: 'rawssport',
    nombre: 'Raws Sport',
    cliente: 'Tienda de ropa deportiva y suplementos · Celaya, Gto.',
    sector: 'Comercio',
    estado: 'propuesta',
    estadoTexto: 'Propuesta + maqueta navegable',
    fecha: 'Sep 2026',
    resumen: 'Tienda en línea con tallas, meses sin intereses, envíos cotizados al momento y panel de ventas, inventario y utilidad real.',
    problema: [
      'Ventas por Instagram y WhatsApp una conversación a la vez: "¿cuánto es con envío?", "te mando el comprobante".',
      'Sin tarjeta ni meses sin intereses se pierde al cliente que no tiene el efectivo hoy.',
      'Inventario, apartados y preventas en notas y capturas; se sabe cuánto se vendió, no cuánto quedó.',
    ],
    solucion: [
      'Tienda con catálogo por línea (ropa, gorras, proteínas, suplementos), stock real por talla, preventas con descuento automático y rastreo del pedido.',
      'Pago con Mercado Pago (tarjeta, hasta 12 MSI, OXXO, SPEI) o PayPal; envío cotizado por código postal con Estafeta, DHL o FedEx.',
      'Panel: Hoy, ¿cuánto me quedó? (vendí − mercancía − gastos − comisiones), mi dinero por cuenta, inventario con reorden, clientes VIP y exportación para el contador.',
      'Modo claro/oscuro automático con la identidad de la marca.',
    ],
    resultado: [
      'Maqueta navegable de 19 pantallas (tienda + panel) y propuesta de 13 páginas entregadas.',
      'Meta: vender 24/7 y ahorrar ~2 h al día en cotizar, confirmar pagos y avisar envíos.',
      'Cada venta alimenta inventario y contabilidad: cero doble captura.',
    ],
    stack: ['HTML/CSS/JS', 'Chart.js', 'Mercado Pago', 'PayPal', 'Cloudflare Pages'],
    url: 'https://rawssport.pages.dev',
    demo: {
      titulo: 'Raws Sport · tienda + panel',
      descripcion: 'Recorre catálogo, ficha, carrito y checkout simulado; luego abre el panel con ventas, inventario y contabilidad.',
      url: 'https://rawssport.pages.dev',
      urlPanel: 'https://rawssport.pages.dev/admin/',
      tipo: 'Maqueta navegable',
      credenciales: null,
    },
  },
  {
    slug: 'koncafe',
    nombre: 'KonCafe',
    cliente: 'Cafetería con app de pedidos y kiosko',
    sector: 'Alimentos',
    estado: 'propuesta',
    estadoTexto: 'Auditoría entregada + plan por versiones',
    fecha: 'Sep 2026',
    resumen: 'Auditoría de seguridad de una app existente hecha por terceros, corrección de lo crítico y plan para evolucionarla por versiones.',
    problema: [
      'La app de clientes y punto de venta (hecha por otro proveedor) exponía la base de clientes completa a cualquiera en internet.',
      'Cualquiera podía inyectar pedidos sin cuenta y el PIN del personal estaba en claro.',
      'El dueño no sabía qué tan grave era ni por dónde empezar.',
    ],
    solucion: [
      'Pentest de caja negra autorizado (13–14 sep 2026): pruebas activas no destructivas sobre Firestore, Auth, Storage, cabeceras y análisis del código publicado.',
      'Informe con severidades y evidencia, runbook de corrección paso a paso y reglas de base de datos listas para desplegar.',
      'Dashboard con las ventas y clientes reconstruidos desde los datos expuestos, para dimensionar el impacto con sus propios números.',
      'Plan por versiones: base segura → cobros blindados → app estable → nueva imagen → pedir-y-recoger con pago móvil. Cada versión se entrega funcionando.',
    ],
    resultado: [
      'Re-test en vivo: fuga de datos personales cerrada (403), inyección de pedidos cerrada y PIN fuera del cliente.',
      'De 3 hallazgos críticos a 0; quedan medios y bajos con plan de corrección.',
      'Prototipo navegable de cómo se vería la app bien construida (cliente, kiosko y panel del gerente).',
    ],
    stack: ['Pentest', 'Firebase (Firestore, Auth, App Check)', 'React + Vite', 'Python', 'Prototipo HTML'],
    url: '',
    demo: {
      titulo: 'KonCafe · prototipo',
      descripcion: 'App del cliente, kiosko de autoservicio y panel del gerente, como se construirían bien. Pestañas reales que funcionan en el teléfono.',
      url: 'demos/koncafe/',
      tipo: 'Prototipo navegable',
      credenciales: null,
    },
  },
  {
    slug: 'gymmachine',
    nombre: 'GymMachine',
    cliente: 'Gimnasios pequeños y medianos',
    sector: 'Fitness',
    estado: 'academico',
    estadoTexto: 'Proyecto académico · código abierto',
    fecha: '2025 – 2026',
    resumen: 'Sistema de gestión de gimnasio: panel de escritorio para el dueño y app Android para administrador, entrenador y miembro, sincronizados en tiempo real.',
    problema: [
      'Los gimnasios pequeños llevan miembros, pagos y vencimientos en hojas de cálculo o cuadernos.',
      'Rutinas y dietas se entregan en papel y nadie da seguimiento al progreso.',
      'La asistencia se controla a ojo.',
    ],
    solucion: [
      'Aplicación de escritorio (JavaFX) para el dueño: indicadores, reportes, historial de pagos y configuración del negocio.',
      'App Android con tres roles: administrador (cobros), entrenador (rutinas y dietas) y miembro (su plan, su progreso).',
      'Asistencia por NFC desde el teléfono y sincronización en tiempo real con Cloud Firestore, sin servidor propio.',
    ],
    resultado: [
      'Dos aplicaciones funcionando sobre la misma base en la nube; cualquier cambio se refleja al instante en los demás dispositivos.',
      'App Android con tres perfiles en una sola instalación: el miembro sigue su rutina y dieta, el entrenador registra mediciones y el dueño cobra y ve reportes.',
      'Documentación completa de base de datos, arquitectura y roles.',
      'Desarrollado en equipo como proyecto final de Tópicos Avanzados de Programación (TecNM Celaya).',
    ],
    stack: ['Java 17', 'JavaFX', 'Kotlin / Android', 'Firebase Firestore', 'Firebase Auth', 'NFC'],
    url: 'https://github.com/Alan20111/GymMachine',
    demo: {
      titulo: 'GymMachine · app móvil',
      descripcion: '28 pantallas reales de la app Android en tres perfiles (miembro, entrenador y dueño), con datos de demostración. Desliza o usa las flechas.',
      url: 'demos/gymmachine/',
      tipo: 'Capturas reales de la app',
      credenciales: null,
    },
  },
];

export const faq = [
  {
    p: '¿Cómo es el soporte?',
    r: 'Directo conmigo por WhatsApp. Durante el desarrollo trabajamos en sprints semanales y ves cada avance funcionando. Después de la entrega hay un periodo de estabilización (normalmente 30 días) y luego soporte mensual con horas de mejoras incluidas. No hay mesa de ayuda ni tickets que nadie contesta.',
  },
  {
    p: '¿El software es mío?',
    r: 'Sí. Al liquidar el proyecto, el código y los datos son tuyos: te entrego el repositorio, los accesos y la documentación. Si algún día quieres llevarlo a otro hosting o con otro desarrollador, puedes hacerlo sin costo.',
  },
  {
    p: '¿Cuánto tarda el desarrollo?',
    r: 'Depende del alcance, pero trabajo con una regla: primero lo que hace dinero. En una tienda o sistema de citas el MVP (ya cobrando) sale en unas 2 semanas y el proyecto completo en 2 a 3 meses. Antes de empezar te entrego una maqueta navegable para que veas exactamente qué vas a recibir.',
  },
  {
    p: '¿Cuánto cuesta y cómo se paga?',
    r: 'Cada propuesta lleva un alcance cerrado y un precio fijo; lo que se sale del alcance se cotiza aparte por hora. Suelo proponer mensualidades sin anticipo a 12 meses que incluyen hosting, dominio y soporte del primer año, dimensionadas para que el sistema se pague con las ventas extra que genera.',
  },
  {
    p: '¿Necesito saber de tecnología?',
    r: 'No. Te entrego el sistema funcionando en tu celular, un manual botón por botón y una capacitación. Tú sigues vendiendo por WhatsApp e Instagram; el sistema hace lo demás.',
  },
  {
    p: '¿Qué pasa con hosting, dominio y correos?',
    r: 'Los incluyo el primer año y los dejo a tu nombre. Uso infraestructura moderna (Cloudflare, Vercel, Firebase, Supabase) que para un negocio local cuesta entre $0 y unos cientos de pesos al año.',
  },
];
